services:
  - type: web
    name: tusuper-api
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: prod
      - key: PORT
        value: "3000"
      - key: SKIP_ENV_FILE
        value: "true"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SEED_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
