sonar.projectKey=Andreycho-B_tusuper-backend
sonar.projectName=tusuper-backend
sonar.organization=andreycho-b
sonar.sources=src
sonar.tests=test,src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.exclusions=dist/**,node_modules/**,**/*.spec.ts,**/*.e2e-spec.ts,**/*.module.ts,src/database/migrations/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
